// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEA3skfwEDb27XJPFg-gUNhxDUlAkaVIs',
    appId: '1:220493221545:web:d80b3430ff2bac35c7a3b8',
    messagingSenderId: '220493221545',
    projectId: 'mobileapp-misiontic-c4',
    authDomain: 'mobileapp-misiontic-c4.firebaseapp.com',
    storageBucket: 'mobileapp-misiontic-c4.appspot.com',
    measurementId: 'G-TSSVG9GK64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHO1H0AMjTS1-NOZa3q4sUNh9RbQHR78',
    appId: '1:220493221545:android:1e2738a2e3701ac0c7a3b8',
    messagingSenderId: '220493221545',
    projectId: 'mobileapp-misiontic-c4',
    storageBucket: 'mobileapp-misiontic-c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wRb448XWMl6KTy5Q8x8b8Ba20lUqBDc',
    appId: '1:220493221545:ios:45af97a4c5a5e48ec7a3b8',
    messagingSenderId: '220493221545',
    projectId: 'mobileapp-misiontic-c4',
    storageBucket: 'mobileapp-misiontic-c4.appspot.com',
    iosClientId: '220493221545-a101ks0t0e8j3846bhhrsgv5tp1493o7.apps.googleusercontent.com',
    iosBundleId: 'udea.edu.co.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-wRb448XWMl6KTy5Q8x8b8Ba20lUqBDc',
    appId: '1:220493221545:ios:45af97a4c5a5e48ec7a3b8',
    messagingSenderId: '220493221545',
    projectId: 'mobileapp-misiontic-c4',
    storageBucket: 'mobileapp-misiontic-c4.appspot.com',
    iosClientId: '220493221545-a101ks0t0e8j3846bhhrsgv5tp1493o7.apps.googleusercontent.com',
    iosBundleId: 'udea.edu.co.mobileapp',
  );
}
